### PR TITLE
Added AtomToastNotification test

### PR DESCRIPTION
**Pull request by andreaevolo**
# Pull Request

## 💬 Context

Please describe the reason to submit this PR.

If there is a related issue, please include its identifier here, preceded by a # character.

## 👩🏼‍🎨 Changes

Please detail which changes are introduced within this PR.

## 💬 Other comments

Optionally, any other relevant comments can be included here.

## 📸 Images

Optionally, images or screenshoots can be included in this section.

### CODE REVIEW

**Comment by andreaevolo** [comment]
I think I messed up with something. I'm sorry , I'm new to opensource 😞

**Comment by oegea** [comment]
> I think I messed up with something. I'm sorry , I'm new to opensource 😞

Do not worry. These things happen when linter rules are changed. 

Let me check and I'll give you some advice about how to fix it.

**Comment by oegea** [comment]
@andreaevolo Hello again!

In order to make your tests properly compile again, you need to check this:

1. Remove line 39 from `src/components/molecules/CopyButton/index.js`. Seems that while solving conflicts you accidentally maintained the component creation twice. No drama, just by deleting line 39 tests start to work again.

However, I've been deeply checking your PR, and I think that it needs some extra work before we're ready to merge. But no drama again, just a little effort more:

1. It's needed to include literals in translation files. Currently, the literal `Copied to the clipboard!` is hardcoded. You can use the literal `El texto se ha copiado correctamente` in Spanish.
2. I'm afraid the current way we're trying to ensure the tab is displayed is not a very clear approach. It's a bit weird to store in a state the latest value copied, and hide the toast when the user tries to copy it again.

Instead, will be better to have an `onClose` callback on the toast component, and  execute it once the toast is hiding, this way the parent will be able to hide the toast in the exact expected moment.

Let me explain this by an example:

**Molecule/CopyButton** Note how we simplify everything, and just have an state that defines if toast should be rendered or not:

Note too that I've removed the `show` property from toast, as it seems redundant.

```jsx
const MoleculesButtonCopy = ({value}) => {
    const [showToast, setShowToast] = useState(false);

    const { t } = useTranslation();

    const copyHandler = () => {
        navigator.clipboard.writeText(value);
        setShowToast(true);
    };

    return (
        <ButtonCopy data-testid="button-copy-element">
            <Button
                label={t('common.Copy')}
                onClick={copyHandler}
                color="black"
                backgroundColor="white"
            />
            { showToast && <AtomToastNotification onClose={() => setShowToast(false)} text="Copied to the clipboard!"/> }
        </ButtonCopy>
    );
};

MoleculesButtonCopy.displayName = 'MoleculesButtonCopy';
MoleculesButtonCopy.propTypes = {
    value: PropTypes.string
};

export default MoleculesButtonCopy;

```

Now, how to implement this on the toast side? 👇 
Note too that I've changed how the duration prop is used. setTimeout had a hardcoded value instead of using the received configuration.

```jsx
const AtomToastNotification = (
    {
        title, 
        text,
        color,
        onClose,
        duration = 5000
    }
) => {
    document.body.style.overflowX = 'hidden';

    // On componentDidMount set the timer
    useEffect(() => {
        const timeId = setTimeout(() => {
            document.body.style.overflowX = 'scroll';
            onClose();
        }, duration);

        return () => {
            clearTimeout(timeId);
        };
    }, []);

    return (
        <ToastNotification color={color} duration={duration}>
            <ToastNotificationCloseBtn onClick={() => onClose()}>
                <Icon
                    size={.8}
                    path={mdiWindowClose}
                    color={'rgb(163 163 163)'}
                />
            </ToastNotificationCloseBtn>
            <div>
                { title && <ToastTitle>{title}</ToastTitle> }
                <p>{text}</p>
            </div>
        </ToastNotification>
    );
};

AtomToastNotification.propTypes = {
    title: PropTypes.string,
    text: PropTypes.string.isRequired,
    type: PropTypes.string,
    onClose: PropTypes.func,
    duration: PropTypes.number
};

AtomToastNotification.defaultProps = {
    show: false,
    duration: 400
};

export default AtomToastNotification;
```

I have doubts too regarding this line:

 `document.body.style.overflowX = 'hidden';` 

because it is not a good practice. However, if we solve all other things, we can merge this PR and keep improving the component on future iterations.

I know that this seems a lot of things to fix. However, you're really close to make it work. These are small changes =) 

Let me know if I can help you in any way more.

Regards,

**Comment by andreaevolo** [comment]
Thank you very much for your time and clarifications, I did a lot of stupid mistakes. I'm gong to fix them.

**Pull request closed without merging**
